### ISSUE TITLE
no connect

### ISSUE THREAD

**Issue by PainFrenemy2** [TheJavaGuy/request-master#22]
[root@2095643-ck23535 httpreq]# make
g++ -c main.cpp -std=c++11
g++ -o http-client HttpRequest.o main.o
[root@2095643-ck23535 httpreq]# ./http-client
App launched!
http request object created!
Webserver address: plugin.null-code.site
Request protocol: https:
Connection port: 443
Final IP Address: 104.21.8.6
Connection ...
Connection established
Sending https: Request ...  Done
Waiting for a response ...  Done

HTTP Response text:
HTTP/1.1 400 Bad Request
Server: cloudflare
Date: Sun, 24 Mar 2024 08:41:50 GMT
Content-Type: text/html
Content-Length: 253
Connection: close
CF-RAY: -

<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>cloudflare</center>
</body>
</html>

Connection closed
request object released!

**Comment by TheJavaGuy** [comment]
This has nothing to do with request-master.
